name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
          channels: bioconda, conda-forge, defaults, anaconda
      
      - name: Setup conda environment on ubuntu-latestüêß
        if: runner.os == 'Linux'
        run: |
          conda create -y -n test-AltExAid python=${{ matrix.python-version }}
      
      - name: Setup conda environment on macos-latest
        if: runner.os == 'macOS'
        run: |
          # ==========================================
          # Use Rosseta for macOS because the Bioconda channel does not yet support Apple Silicon
          # ==========================================
          CONDA_SUBDIR=osx-64 conda create -y -n test-AltExAid python=${{ matrix.python-version }}
          conda activate test-AltExAid
          conda config --env --set subdir osx-64

      - name: Install dependencies
        run: |
          conda activate test-AltExAid
          python -m pip install --upgrade pip pytest numpy pandas 

      - name: Run pytest
        env:
          PYTHONPATH: src
        run: |
          conda activate test-AltExAid
          python -m pytest tests -p no:warnings -vv

